[programs.localnet]
sale = "HD91U2CVgTcStNZKwE78ni2oHTYcF34wZHM2nRFKhD5K"

[registry]
url = "https://anchor.project-serum.com"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/mainnet-deployer.json"

[workspace]
members = ["programs/sale"]
